import os
import json
import requests
import sys

GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN')
GITHUB_REPOSITORY = os.environ.get('GITHUB_REPOSITORY')
GITHUB_PR_NUMBER = os.environ.get('PR_NUMBER')
GITHUB_SHA = os.environ.get('GITHUB_SHA')

# Read feedback from a file generated by your analysis script (e.g., pr-line-comments.json)
# The file should be a list of dicts: {"path": ..., "line": ..., "body": ..., "side": "RIGHT"}
if not os.path.exists('pr-line-comments.json'):
    print('No pr-line-comments.json found. Skipping line-level comments.')
    sys.exit(0)

with open('pr-line-comments.json', 'r', encoding='utf-8') as f:
    feedback = json.load(f)

api_url = f"https://api.github.com/repos/{GITHUB_REPOSITORY}/pulls/{GITHUB_PR_NUMBER}/comments"
headers = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}

for comment in feedback:
    data = {
        "body": comment["body"],
        "commit_id": GITHUB_SHA,
        "path": comment["path"],
        "side": comment.get("side", "RIGHT"),
        "line": comment["line"]
    }
    response = requests.post(api_url, headers=headers, data=json.dumps(data))
    print(f"Comment on {comment['path']}:{comment['line']} - Status: {response.status_code}")
    if response.status_code >= 300:
        print(response.text)
